apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-api-hpa
  labels:
    system: node-app
    app: node-app-api
    environment: production
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: node-app-api-deployment
 minReplicas: 3
 maxReplicas: 8
 targetCPUUtilizationPercentage: 50