apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-app-api-sa
  labels:
    system: node-app
    app: node-app-api
    environment: production
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: IDENTITY_CLIENT_ID
    azure.workload.identity/tenant-id: IDENTITY_TENANT_ID