apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-api-configmap
  labels:
    system: node-app
    app: node-app-api
    environment: production
data:
  ENVIRONMENT: Production
  DATABASE_SERVER: host.docker.internal
  DATABASE_NAME: NodeApp
  DATABASE_AUTH_TYPE: password
  DATABASE_USERNAME: sa
  DATABASE_PASSWORD: SA-P@ssw0rd
  DATABASE_HEALTHCHECK_QUERY: SELECT @@VERSION
