apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "utils.labels" . | indent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
{{ include "utils.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.buildNumber }}"
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # TODO: More?
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          readinessProbe:
            httpGet:
              path: /system/ping
              port: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /system/ping
              port: {{ .Values.port }}