apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "utils.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /node-app/api(/|$)(.*)
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: 80