apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "utils.labels" . | indent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.managedIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.serviceAccount.managedIdentity.tenantId }}