apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "utils.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.port }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}